export const flagEmojis = {
  "🚗": "Car",
  "🚓": "Police Car",
  "🚕": "Taxi",
  "🛺": "Auto Rickshaw",
  "🚙": "Sport utility vehicle",
  "🚌": "Bus",
  "🚐": "Minibus",
  "🚎": "Trolley Bus",
  "🚑": "Ambulance",
  "🚒": "Fire Engine",
  "🚚": "Delivery van",
  "🚛": "Articulated Lorry",
  "🚜": "Tractor",
  "🚘": "oncoming car",
  "🚔": "oncoming police car",
  "🚖": "oncoming taxi",
  "🚍": "oncoming bus",
  "🦽": "Manual wheel chair",
  "🦼": "Motorized wheel chair",
  "🛹": "Skateboard",
  "🚲": "Bicycle",
  "🛴": "Kick Scooter",
  "🛵": "Motor Scooter",
  "🏍": "Motorcycle",
  "🏎": "Racing car",
  "🚄": "High-speed train",
  "🚅": "Bullet train",
  "🚈": "Light rail",
  "🚝": "Monorail",
  "🚞": "Mountain railway",
  "🚃": "Railway Carriage",
  "🚋": "Tram Car",
  "🚆": "Train",
  "🚇": "Metro",
  "🚠": "Mountain cableway",
  "🚂": "Locomotive",
  "🛩": "Small Aeroplane",
  "🪂": "Parachute",
  "✈": "Aeroplane",
  "💺": "Seat",
  "🚁": "Helicopter",
  "🚀": "Rocket",
  "🛸": "Flying Saucer",
  "🛰": "Satellite",
  "⛵": "Sailing Boat",
  "🚤": "Speed Boat",
  "⛴": "Ferry",
  "🚢": "Ship",
  "🛳": "Passenger Ship",
};
